version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./data/redis.conf:/etc/redis/redis.conf
  sentinel1:
    image: redis:7
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    depends_on:
      - redis
    ports:
      - "26379:26379"
    volumes:
      - ./data/sentinel.conf:/etc/redis/sentinel.conf
  sentinel2:
    image: redis:7
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    depends_on:
      - redis
    ports:
      - "26380:26379"
    volumes:
      - ./data/sentinel.conf:/etc/redis/sentinel.conf
  sentinel3:
    image: redis:7
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    depends_on:
      - redis
    ports:
      - "26381:26379"
    volumes:
      - ./data/sentinel.conf:/etc/redis/sentinel.conf
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./data/loki:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./tools/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    restart: unless-stopped

  nodeexporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana
      # Add your app services here, e.g.:
      # - dashboard
      # - api
    restart: unless-stopped
