"""Add JobApplication model

Revision ID: 38aeab4cb663
Revises: 79bb9fad7e9b
Create Date: 2025-07-28 09:23:45.171589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38aeab4cb663'
down_revision: Union[str, Sequence[str], None] = '79bb9fad7e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'file_metadata', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_metadata', type_='foreignkey')
    # ### end Alembic commands ###
