"""add 2fa fields to user model

Revision ID: 4a1500cee855
Revises: 56f04ab08eba
Create Date: 2025-07-24 20:13:20.890076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1500cee855'
down_revision: Union[str, Sequence[str], None] = '56f04ab08eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('two_fa_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('two_fa_method', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_fa_method')
    op.drop_column('users', 'two_fa_secret')
    op.drop_column('users', 'two_fa_enabled')
    # ### end Alembic commands ###
