"""Add validation constraints to models

Revision ID: 4ae7bae280b1
Revises: 242bfb2cc70f
Create Date: 2025-07-24 19:17:00.827119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae7bae280b1'
down_revision: Union[str, Sequence[str], None] = '242bfb2cc70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('experience', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_preferences', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_preferences', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('experience', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('education', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
