""""Initial migration"

Revision ID: 4b100924591d
Revises: ce9da821a1d1
Create Date: 2025-07-20 22:19:50.109893

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '4b100924591d'
down_revision: Union[str, Sequence[str], None] = 'ce9da821a1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
