"""Add file metadata table for storage tracking

Revision ID: 56f04ab08eba
Revises: 4ae7bae280b1
Create Date: 2025-07-24 19:23:35.986644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f04ab08eba'
down_revision: Union[str, Sequence[str], None] = '4ae7bae280b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metadata_filename'), 'file_metadata', ['filename'], unique=False)
    op.create_index(op.f('ix_file_metadata_uploaded_at'), 'file_metadata', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_file_metadata_user_id'), 'file_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_metadata_user_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_uploaded_at'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_filename'), table_name='file_metadata')
    op.drop_table('file_metadata')
    # ### end Alembic commands ###
