"""Add JobApplication model

Revision ID: 79bb9fad7e9b
Revises: c7b6afbdb1b5
Create Date: 2025-07-28 09:13:03.965136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bb9fad7e9b'
down_revision: Union[str, Sequence[str], None] = 'c7b6afbdb1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['file_metadata.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    op.add_column('job_preferences', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.add_column('job_preferences', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('job_preferences', sa.Column('notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('profile_visibility', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('show_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_step', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'onboarding_complete')
    op.drop_column('users', 'show_email')
    op.drop_column('users', 'profile_visibility')
    op.drop_column('job_preferences', 'notifications')
    op.drop_column('job_preferences', 'location')
    op.drop_column('job_preferences', 'job_type')
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
