""""Add profile_completeness to User model"

Revision ID: 7fcd6c247fd7
Revises: f7e561fc4769
Create Date: 2025-08-07 17:48:28.469678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fcd6c247fd7'
down_revision: Union[str, Sequence[str], None] = 'f7e561fc4769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'details')
    op.drop_index(op.f('ix_job_listings_application_status'), table_name='job_listings')
    op.drop_column('job_listings', 'is_applied')
    op.drop_column('job_listings', 'application_status')
    op.add_column('users', sa.Column('profile_completeness', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completeness')
    op.add_column('job_listings', sa.Column('application_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_listings', sa.Column('is_applied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_job_listings_application_status'), 'job_listings', ['application_status'], unique=False)
    op.add_column('audit_log', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
