""""Add user profile, education, experience, projects, and job preferences models"

Revision ID: ce9da821a1d1
Revises: 7817cb5869b5
Create Date: 2025-07-19 21:55:16.451132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9da821a1d1'
down_revision: Union[str, Sequence[str], None] = '7817cb5869b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('onboarding_step', sa.String(length=50), nullable=True))
    op.add_column('job_preferences', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.add_column('job_preferences', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('job_preferences', sa.Column('notifications', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_preferences', 'notifications')
    op.drop_column('job_preferences', 'location')
    op.drop_column('job_preferences', 'job_type')
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'onboarding_complete')
    # ### end Alembic commands ###
