""""Add user profile, education, experience, projects, and job preferences models"

Revision ID: ce9da821a1d1
Revises: 7817cb5869b5
Create Date: 2025-07-19 21:55:16.451132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9da821a1d1'
down_revision: Union[str, Sequence[str], None] = '7817cb5869b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
