server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job-applier-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: job-applier
          __path__: /Users/kartikgarg/Downloads/JOB APPLIER/output/centralized.log
